config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'devise/admins/sessions',
    passwords: 'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'devise/users/sessions',
    passwords: 'devise/users/passwords',
    registrations: 'devise/users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Admin側
  namespace :admin do
    # TopページをHomeに変更
    get '/' => 'homes#top'
    # get "search/homes" => "homes#search", as: 'homes_search'

    get 'comics/:isbn' => 'comics#show', as: 'comic'
    get 'comics/:isbn/edit' => 'comics#edit', as: 'comic_edit'
    patch 'comics/:isbn' => 'comics#update', as: 'comic_update'
    delete 'comics/:isbn' => 'comics#destroy', as: 'comic_destroy'
    get 'search/comics' => 'comics#search', as: 'comics_search'
    resources :comics, only: %i[index create]

    resources :categories, except: %i[new show destroy]
    resources :users, only: %i[index show]
  end

  # User側
  scope module: :public do
    # Topページ
    root to: 'homes#top'
    # aboutページ
    get 'homes/about' => 'homes#about'
    # user周りのルート
    resources :users, except: %i[new create destroy]
    get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
    get 'search' => 'users#search', as: 'user_search'
    # フォロー機能
    resources :relationships, only: %i[create destroy]
    get 'relationships/follows' => 'relationships#follow', as: 'relationships_follows'
    get 'relationships/followers' => 'relationships#follower', as: 'relationships_followers'
    # Comic関連のルーティング
    # カテゴリー検索
    get 'category/search' => 'homes#search', as: 'search_comics'
    get 'comics/:isbn' => 'comics#show', as: 'comic'
    resources :comics, only: [:index] do
      # レビュー機能
      resources :reviews do
        resources :comments, only: %i[create destroy]
        resource :likes, only: %i[create destroy]
      end
      # Tag機能
      resources :tags, only: %i[create destroy] # do
      # get 'search', to: 'tag#search'
      # end
    end
    get 'tags/:tag_name/search' => 'tags#search', as: 'tag_search'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top; end

  # def search
  #   @comics = Comic.search(params[:search])
  # end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_search_form.html.erb
<%= form_with url: admin_homes_search_path, :method => 'get', local: true do  |f| %>
  <%= f.text_field :search, size: 40, placeholder: "コミック検索" %>
  <%= f.submit "検索", :name => nil, class: "btn btn-outline-secondary btn-sm" %>
<% end %>

app/views/admin/homes/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <h2>コミック検索</h2>
        <!--コミック一覧-->
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>カテゴリー</th>
              <th>タイトル</th>
              <th>作者</th>
              <th>出版社</th>
            </tr>
          </thead>
          <tbody>
            <% @comics.each do |comic| %>
              <tr>
                <td>
                  <%= link_to admin_comic_path(comic.isbn) do %>
                    <%= image_tag comic.image_url, size: "44x60" %>
                  <% end %>
                </td>
                <td><%= comic.category.name %></td>
                <td>
                  <%= link_to admin_comic_path(comic.isbn) do %>
                    <%= comic.title %>
                  <% end %>
                </td>
                <td><%= comic.author %></td>
                <td><%= comic.publisher %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<!-- 管理人のTopページ -->
<div class="container">
  <div class="row">
    <div class="col-lg-10 top-box">
      <h2 class="top-title">管理者用</h2>
      <div>
        <%= link_to admin_comics_search_path do %>
          <p class="top-path">コミック新規登録</p>
        <% end %>
      </div>
      <div>
        <%= link_to admin_comics_path do %>
          <p class="top-path">コミック一覧</p>
        <% end %>
      </div>
      <div>
        <%= link_to admin_categories_path do %>
          <p class="top-path">カテゴリー登録/一覧</p>
        <% end %>
      </div>
    </div>
  </div>
 </div>