config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'devise/admins/sessions',
    passwords: 'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'devise/users/sessions',
    passwords: 'devise/users/passwords',
    registrations: 'devise/users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Admin側
  namespace :admin do
    # TopページをHomeに変更
    get '/' => 'homes#top'
    # get "search/homes" => "homes#search", as: 'homes_search'

    get 'comics/:isbn' => 'comics#show', as: 'comic'
    get 'comics/:isbn/edit' => 'comics#edit', as: 'comic_edit'
    patch 'comics/:isbn' => 'comics#update', as: 'comic_update'
    delete 'comics/:isbn' => 'comics#destroy', as: 'comic_destroy'
    get 'search/comics' => 'comics#search', as: 'comics_search'
    resources :comics, only: %i[index create]

    resources :categories, except: %i[new show destroy]
    resources :users, only: %i[index show]
  end

  # User側
  scope module: :public do
    # Topページ
    root to: 'homes#top'
    # aboutページ
    get 'homes/about' => 'homes#about'
    # user周りのルート
    resources :users, except: %i[new create destroy]
    get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
    get 'search' => 'users#search', as: 'user_search'
    # フォロー機能
    resources :relationships, only: %i[create destroy]
    get 'relationships/follows' => 'relationships#follow', as: 'relationships_follows'
    get 'relationships/followers' => 'relationships#follower', as: 'relationships_followers'
    # Comic関連のルーティング
    # カテゴリー検索
    get 'category/search' => 'homes#search', as: 'search_comics'
    get 'comics/:isbn' => 'comics#show', as: 'comic'
    resources :comics, only: [:index] do
      # レビュー機能
      resources :reviews do
        resources :comments, only: %i[create destroy]
        resource :likes, only: %i[create destroy]
      end
      # Tag機能
      resources :tags, only: %i[create destroy] # do
      # get 'search', to: 'tag#search'
      # end
    end
    get 'tags/:tag_name/search' => 'tags#search', as: 'tag_search'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comics, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'カテゴリーを追加しました'
      redirect_back(fallback_location: root_path)
    else
      render :index
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'カテゴリーを変更しました'
      redirect_to admin_categories_path(@category.id)
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <h4 class="text-center">カテゴリー編集</h4>
      <div style="font-size: 20px;">
        <%= render "layouts/error_messages", model: @category %>
      </div>

      <!--編集フォーム-->
      <%= form_with model: @category, url: admin_category_path(@category.id), local: true do |f| %>
        <table class="table">
          <tr class="category-table-box">
            <th><%= f.label "カテゴリー名" %></th>
            <td><%= f.text_field :name, class: "form-control", :size => "70x2" %></td>
          </tr>
        </table>
        <div class="text-center">
          <%= f.submit "更新する", class: "btn btn-outline-secondary btn-lg" %>
        </div>
      <% end %>

    </div>
  </div>
  <div class="row">
    <div class="col-lg-10 text-center">
      <%= link_to admin_categories_path do %>
        <p class="category-path">カテゴリー登録  /  一覧</p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <!-- カテゴリーの新規登録フォーム -->
    <div class="col-lg-4">
      <%= form_with model: @category, url: admin_categories_path, method: :post, local: true do |f| %>
         <div class="category-title">
           <%= f.label "カテゴリー登録" %>
         </div>
         <div style="font-size: 20px;">
           <%= render "layouts/error_messages", model: @category %>
         </div>
         <div>
           <%= f.text_field :name, placeholder: "ここに入力", class: "form-control" %>
         </div>
         <div class="form-btn">
           <%= f.submit "登録する", class: "btn btn-outline-secondary btn-lg ml-3 mt-3" %>
         </div>
      <% end %>
    </div>
    <div class="col-lg-2"></div>
    <!-- カテゴリー一覧表示 -->
    <div class="col-lg-6">
      <p class="category-index-title">カテゴリー一覧</p>
      <table class="table">
        <thead>
          <tr>
            <th>カテゴリー名</th>
            <th class=""></th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td>
                <%= category.name %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_category_path(category.id), class: "btn btn-outline-secondary" %>
              </td>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
        </tfoot>
      </table>
    </div>

  </div>
</div>