config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'devise/admins/sessions',
    passwords: 'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'devise/users/sessions',
    passwords: 'devise/users/passwords',
    registrations: 'devise/users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Admin側
  namespace :admin do
    # TopページをHomeに変更
    get '/' => 'homes#top'
    # get "search/homes" => "homes#search", as: 'homes_search'

    get 'comics/:isbn' => 'comics#show', as: 'comic'
    get 'comics/:isbn/edit' => 'comics#edit', as: 'comic_edit'
    patch 'comics/:isbn' => 'comics#update', as: 'comic_update'
    delete 'comics/:isbn' => 'comics#destroy', as: 'comic_destroy'
    get 'search/comics' => 'comics#search', as: 'comics_search'
    resources :comics, only: %i[index create]

    resources :categories, except: %i[new show destroy]
    resources :users, only: %i[index show]
  end

  # User側
  scope module: :public do
    # Topページ
    root to: 'homes#top'
    # aboutページ
    get 'homes/about' => 'homes#about'
    # user周りのルート
    resources :users, except: %i[new create destroy]
    get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
    get 'search' => 'users#search', as: 'user_search'
    # フォロー機能
    resources :relationships, only: %i[create destroy]
    get 'relationships/follows' => 'relationships#follow', as: 'relationships_follows'
    get 'relationships/followers' => 'relationships#follower', as: 'relationships_followers'
    # Comic関連のルーティング
    # カテゴリー検索
    get 'category/search' => 'homes#search', as: 'search_comics'
    get 'comics/:isbn' => 'comics#show', as: 'comic'
    resources :comics, only: [:index] do
      # レビュー機能
      resources :reviews do
        resources :comments, only: %i[create destroy]
        resource :likes, only: %i[create destroy]
      end
      # Tag機能
      resources :tags, only: %i[create destroy] # do
      # get 'search', to: 'tag#search'
      # end
    end
    get 'tags/:tag_name/search' => 'tags#search', as: 'tag_search'
  end
end

app/models/comic.rb
class Comic < ApplicationRecord
  self.primary_key = 'isbn' # <== API使用のため
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :tags, dependent: :destroy

  # バリデーション
  validates :title, presence: true, uniqueness: true
  validates :author, presence: true
  validates :publisher, presence: true
  validates :category_id, presence: true

  # レビュー平均
  def avg_rate
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f
    end
  end

  def review_rate_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f * 100 / 5
    end
  end

  # 検索
  ## User
  def self.search(search, user_or_comic, how_search)
    if user_or_comic == '2'
      if how_search == '1'
        Comic.where(['title LIKE ?', "%#{search}%"])
      elsif how_search == '2'
        Comic.where(['title LIKE ?', "%#{search}"])
      elsif how_search == '3'
        Comic.where(['title LIKE ?', "#{search}%"])
      elsif how_search == '4'
        Comic.where(['title LIKE ?', search.to_s])
      else
        Comic.all
      end
    end
  end
  ## Admin
  # def self.search(search)
  #   return Comic.all unless search
  #   Comic.where(['title LIKE ?', "%#{search}%"])
  # end
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_action :authenticate_admin!

  def search
    @categories = Category.all
    # からの配列を作る
    @comics = []
    @title = params[:title]
    if @title.present?
      # ここでresultsに楽天APIから取得したデータを格納する
      results = RakutenWebService::Books::Book.search({
                                                        title: @title
                                                      })
      # ここで@comicsにAPIから取得したJSONデータを格納する
      results.each do |result|
        comic = Comic.new(read(result))
        @comics << comic
      end
    end
  end

  def create
    comic = Comic.find_or_initialize_by(isbn: params[:isbn])
    # @comics内の各データをそれぞれ保存する/すでに保存済のものは除外？
    unless comic.persisted?
      results = RakutenWebService::Books::Book.search(isbn: comic.isbn)
      comic = Comic.new(comic_params)
      if  comic.save
        redirect_to admin_comics_path, notice: 'コミックを追加しました'
      else
        render :search
      end
    end
  end

  def index
    @comics = Comic.all
  end

  def show
    @comic = Comic.find_by(isbn: params[:isbn])
  end

  def edit
    @comic = Comic.find_by(isbn: params[:isbn])
    @categories = Category.all
  end

  def update
    @comic = Comic.find_by(isbn: params[:isbn])
    if @comic.update!(comic_params)
      redirect_to admin_comic_path(@comic.isbn), notice: '更新しました'
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @comic = Comic.find_by(isbn: params[:isbn])
    @comic.destroy
    redirect_to admin_comics_path, notice: '削除しました'
  end

  private

  def comic_params
    params.require(:comic).permit(
      :category_id,
      :body,
      :title,
      :author,
      :publisher,
      :url,
      :isbn,
      :image_url,
      :item_caption
    )
  end

  def read(result)
    title = result['title']
    author = result['author']
    publisher = result['publisherName']
    url = result['itemUrl']
    isbn = result['isbn']
    image_url = result['mediumImageUrl'].gsub('?_ex=120x120', '')
    item_caption = result['itemCaption']
    {
      title: title,
      author: author,
      publisher: publisher,
      url: url,
      isbn: isbn,
      image_url: image_url,
      item_caption: item_caption
    }
  end
end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/views/admin/comics/edit.html.erb
<div class="container-fluid comic-page-box">
  <div class="row">
    <div class="col-lg-4">
      <p><%= image_tag @comic.image_url, size: "370x500" %></p>
    </div>

      <!-- コミック編集フォーム -->
  <%= form_with model: @comic, url: admin_comic_update_path(@comic.isbn), method: :patch, local: true do |f| %>
    <div class="col-lg-6">
      <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>コミック情報編集</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= f.label "タイトル" %></td>
              <td><%= f.text_field :title, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label "作者" %></td>
              <td><%= f.text_field :author, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label "出版社" %></td>
              <td><%= f.text_field :publisher, class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= f.label "ストーリー" %></td>
              <td><%= f.text_area :item_caption, class: "form-control", :size => "100x5" %></td>
            </tr>
            <tr>
              <td><%= f.label "カテゴリー" %></td>
              <td><%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "--選択してください--") %></td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td></td>
              <td><%= f.submit "更新する", class: "btn btn-outline-secondary btn-lg" %></td>
            </tr>
          </tfoot>
      </table>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/comics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 comic-page-box">
      <h3 class="comic-index-title">コミック一覧</h3>
      <!--新規登録遷移-->
      <div class="comic-path-box">
        <%= link_to admin_comics_search_path do %>
          <p class="comic-path">コミック新規登録へ</p>
        <% end %>
      </div>

      <!--コミック一覧-->
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>カテゴリー</th>
            <th>タイトル</th>
            <th>作者</th>
            <th>出版社</th>
          </tr>
        </thead>
        <tbody>
          <% @comics.each do |comic| %>
            <tr>
              <td>
                <%= link_to admin_comic_path(comic.isbn) do %>
                  <%= image_tag comic.image_url, size: "44x60" %>
                <% end %>
              </td>
              <td><%= comic.category.name %></td>
              <td>
                <%= link_to admin_comic_path(comic.isbn) do %>
                  <%= comic.title %>
                <% end %>
              </td>
              <td><%= comic.author %></td>
              <td><%= comic.publisher %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/comics/search.html.erb
<div class="container">
  <div class="row">

    <!--検索フォーム-->
    <div class="col-lg-5">

      <%= form_tag(admin_comics_search_path, method: :get) do %>
        <p class="form-box"><%= text_field_tag :title, @title, :size => "50x2" %></p>
        <p class="form-btn"><%= submit_tag "検索", class: "btn btn-outline-secondary btn-lg" %></p>
      <% end %>
    </div>

    <!--検索結果表示-->
    <div class="col-lg-7 search-index">
      <% if @comics %>
        <% @comics.each do |comic| %>
          <!--コミックイメージ-->
          <p><%= image_tag comic.image_url, size: "220x300" %></p>
          <!--コミックタイトル-->
          <p><%= comic.title %></p>
          <!--作者-->
          <p><%= comic.author %></p>
          <!--出版社-->
          <p><%= comic.publisher %></p>
          <!--あらすじ-->
          <p><%= comic.item_caption %></p>
          <!--保存-->
          <div>
            <%= form_with model: comic, url: admin_comics_path, method: :post, local: true  do |f| %>
              <p><%= f.hidden_field :isbn, :value => comic.isbn %></p>
              <p><%= f.hidden_field :url, :value => comic.url %></p>
              <p><%= f.hidden_field :image_url, :value => comic.image_url %></p>
              <p><%= f.hidden_field :title, :value => comic.title %></p>
              <p><%= f.hidden_field :author, :value => comic.author %></p>
              <p><%= f.hidden_field :publisher, :value => comic.publisher %></p>
              <p><%= f.hidden_field :item_caption, :value => comic.item_caption %></p>
              <p><%= f.label "カテゴリー" %></p>
              <p><%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "--選択してください--") %></>
              <p class="result-btn"><%= f.submit 'データを保存する', class: "btn btn-outline-secondary btn-sm" %></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/comics/show.html.erb
<div class="container-fluid comic-page-box">
  <div class="row">
    <!--コミック画像-->
    <div class="col-lg-4">
      <%= image_tag @comic.image_url, size: "370x500" %>
    </div>

    <!--コミック詳細-->
    <div class="col-lg-6">
      <table class="table">
        <thead>
          <tr>
            <th width="120px"></th>
            <th>コミック情報</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>タイトル</td>
            <td><%= @comic.title %></td>
          </tr>
          <tr>
            <td>作者</td>
            <td><%= @comic.author %></td>
          </tr>
          <tr>
            <td>出版社</td>
            <td><%= @comic.publisher %></td>
          </tr>
          <tr>
            <td>カテゴリー</td>
            <td><%= @comic.category.name %></td>
          </tr>
          <tr>
            <td>ストーリー</td>
            <td>
              <%= @comic.item_caption %>
            </td>
          </tr>
        <tfoot>
          <tr>
            <td></td>
            <td>
              <!--編集ボタン-->
              <p class="comic-btn">
                <%= link_to "編集する", admin_comic_edit_path(@comic.isbn), class: "btn btn-outline-secondary btn-lg" %>
              </p>
              <!--削除ボタン-->
              <p class="comic-btn">
                <%= link_to "削除する", admin_comic_destroy_path(@comic.isbn), method: :delete, class: "btn btn-outline-danger btn-lg" %>
              </p>
            </td>
          </tr>
        </tfoot>
      </table>

    </div>
  </div>
</div>