config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'devise/admins/sessions',
    passwords: 'devise/admins/passwords',
    registrations: 'devise/admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'devise/users/sessions',
    passwords: 'devise/users/passwords',
    registrations: 'devise/users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Admin側
  namespace :admin do
    # TopページをHomeに変更
    get '/' => 'homes#top'
    # get "search/homes" => "homes#search", as: 'homes_search'

    get 'comics/:isbn' => 'comics#show', as: 'comic'
    get 'comics/:isbn/edit' => 'comics#edit', as: 'comic_edit'
    patch 'comics/:isbn' => 'comics#update', as: 'comic_update'
    delete 'comics/:isbn' => 'comics#destroy', as: 'comic_destroy'
    get 'search/comics' => 'comics#search', as: 'comics_search'
    resources :comics, only: %i[index create]

    resources :categories, except: %i[new show destroy]
    resources :users, only: %i[index show]
  end

  # User側
  scope module: :public do
    # Topページ
    root to: 'homes#top'
    # aboutページ
    get 'homes/about' => 'homes#about'
    # user周りのルート
    resources :users, except: %i[new create destroy]
    get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
    patch 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
    get 'search' => 'users#search', as: 'user_search'
    # フォロー機能
    resources :relationships, only: %i[create destroy]
    get 'relationships/follows' => 'relationships#follow', as: 'relationships_follows'
    get 'relationships/followers' => 'relationships#follower', as: 'relationships_followers'
    # Comic関連のルーティング
    # カテゴリー検索
    get 'category/search' => 'homes#search', as: 'search_comics'
    get 'comics/:isbn' => 'comics#show', as: 'comic'
    resources :comics, only: [:index] do
      # レビュー機能
      resources :reviews do
        resources :comments, only: %i[create destroy]
        resource :likes, only: %i[create destroy]
      end
      # Tag機能
      resources :tags, only: %i[create destroy] # do
      # get 'search', to: 'tag#search'
      # end
    end
    get 'tags/:tag_name/search' => 'tags#search', as: 'tag_search'
  end
end

app/views/layouts/_category.html.erb
<div class="category-area container">
  <div class="row m-0">
    <div class="category-box col-lg-12 m-3">
      <% categories.each do |category| %>
        <%= link_to search_comics_path(id: category.id) do %>
          <div class="category-name card">
            <div class="category-text"><%= category.name %></div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li style="color: red;"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<span class="foot-text"><%= image_tag 'Rev.com-logo-2.png', :size => "80x80" %> All right reserved by MinO</span>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg ">
    <buttun class="navbar-toggler" type="buttun" data-toggle="collapse" data-target="#navbarVavDropdown" aria-controls="nabarNavDropdown" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </buttun>

    <div class="collapse navbar-collapse text-light" id="navbarNavDropdown">

      <ul class="navbar-nav">

        <!-- userがログイン時-->
        <% if user_signed_in? %>
        <p class="drawer">
          <%= link_to root_path do %>
            <p class="head-logo"><%= image_tag 'Rev.com-logo-2.png', :size => "100x100" %></p>
          <% end %>
          <div id="hm-icon">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
        </p>
        <div class="collapse navbar-collapse justify-content-end menu" id="sp-menu">
          <ul class="head-path-box">
            <li class="nav-item">
                <%= link_to homes_about_path do %>
                  <p class="user-head-path">Rev.comとは？</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to user_path(current_user) do %>
                  <p class="user-img-path">
                    <!--Mypage-->
                    <%= attachment_image_tag current_user, :profile_image, size: "50x50", format: 'jpg', fallback: "no_image.jpg", class: "rounded-circle" %>
                    <%= current_user.name %>
                  </p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <p class="user-head-path">ログアウト</p>
                <% end %>
            </li>
          </ul>
        </div>

        <!-- 管理人がログイン時 -->
        <% elsif admin_signed_in? %>
        <p class="drawer">
          <%= link_to admin_path do %>
            <p class="head-logo"><%= image_tag 'Rev.com-logo-2.png', :size => "100x100" %></p>
          <% end %>
          <div id="hm-icon">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
        </p>
        <div class="collapse navbar-collapse justify-content-end" id="sp-menu">
          <ul class="head-path-box">
            <li class="nav-item">
                <%= link_to admin_comics_search_path do %>
                  <p class="admin-head-path">コミック新規登録</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to admin_comics_path do %>
                  <p class="admin-head-path">コミック一覧</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to admin_categories_path do %>
                  <p class="admin-head-path">カテゴリー登録/一覧</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete do %>
                  <p class="admin-head-path">ログアウト</p>
                <% end %>
            </li>
          </ul>
        </div>

        <!-- どちらもログインしていない時 -->
        <% else %>
        <p class="drawer">
          <%= link_to root_path do %>
            <p class="head-logo"><%= image_tag 'Rev.com-logo-2.png', :size => "100x100" %></p>
          <% end %>
          <div id="hm-icon">
            <a class="menu-trigger" href="#">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
        </p>
        <div class="collapse navbar-collapse justify-content-end" id="sp-menu">
          <ul class="head-path-box">
            <li class="nav-item">
                <%= link_to homes_about_path do %>
                  <p class="default-head-path">Rev.comとは？</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to new_user_registration_path do %>
                  <p class="default-head-path">新規登録</p>
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to new_user_session_path do %>
                  <p class="default-head-path">ログイン</p>
                <% end %>
            </li>
          </ul>
        </div>

        <% end %>

      </ul>

    </div>

  </nav>

</header>
<div class="row p-0 m-0">
  <div class="head-search col-lg-12 p-0 m-0">
    <% if admin_signed_in? %>
      <!--%= render 'admin/homes/search_form' %>-->
    <% else %>
      <%= render 'public/users/search_form' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rev.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">

    <script src="https://kit.fontawesome.com/31bd3b6efb.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--<link href="path/bxslider/jquery.bxslider.css" rel="stylesheet" type="text/css">-->
    <!--<script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <!--Header-->
    <%= render "layouts/header" %>

    <!--Flash Message-->
    <% if flash[:notice] %>
      <div class="notification text-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notification text-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div class="main">
      <%= yield %>


      <!--<script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>-->
      <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>-->

      <!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </div>
    <footer class="text-light">
      <div class="footer-box">
        <%= render 'layouts/footer' %>
      </div>
    </footer>
  </body>
</html>